version: '3'

services:
     freeradius:
         image: roddie/cisco-sda-freeradius:latest
         container_name: freeradius
         ports:
             - "1812-1813:1812-1813/udp"
         volumes:
             - "./freeradius/clients.conf:/etc/raddb/clients.conf"
             - "./freeradius/users:/etc/raddb/mods-config/files/authorize"
         restart: unless-stopped
